# Generated by Django 5.1.4 on 2024-12-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_attemptmailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
